---
title: rails
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
subtitle: and beyond
email: hi@bgvo.io
description: This section was in the initial template and I thought it was a good
  idea to keep it. Right now I'm not sure what to put here. But, I'll figure it out.
baseurl: ''
url: ''
twitter_username: borjagvo
github_username: bgvo
theme: minima
plugins:
- jekyll-feed
sass:
  style: compressed
  sass_dir: _sass
  cache: false
  load_paths:
  - _sass
  - _sass/minima
